// app/layout.tsx
import './globals.css'
import { dark } from '@clerk/themes';
import { Outfit } from 'next/font/google'
import { ClerkProvider, SignIn, SignedIn, SignedOut } from '@clerk/nextjs'
import Navbar from '@/components/Navbar'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={{
        baseTheme: dark
      }}>
      <html lang="en">
        <body className={outfit.className}>
          <SignedIn>
            <Navbar/>
            {children} 
          </SignedIn>
          <SignedOut>
            <SignIn/>
          </SignedOut>
          </body>
      </html>
    </ClerkProvider>
  )
}
